version: "3.7"
services:
  mq:
    container_name: mq
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: mq1
      MQ_APP_PASSWORD: password123
    volumes:
      - type: volume
        source: qm1data
        target: /mnt/mqm
    command: ["run"]
volumes:
  qm1data:

# https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-containers/#step-2-get-the-mq-in-docker-image
# https://developer.ibm.com/components/ibm-mq/articles/mq-downloads/ 
# https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q029500_.html
