version: '3.7'
services:
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redis-data:/db
volumes:
  redis-data: # https://collabnix.com/running-redisinsight-using-docker-compose/
