version: "3.7"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
      - POSTGRES_DB=todo
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/
volumes:
  postgres-data: