version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "/redis.conf"]
    volumes:
      - type: volume
        source: redis-data
        target: /redis.conf
        
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "3001:8081"
volumes:
  redis-data:
